// src/scenes/presets.ts

export interface IRParams {
  decayTime: number;    // reverb tail length in seconds
  preDelayMs: number;   // pre-delay before reverb starts
  roomSize: number;     // 0-1, room size factor
  damping: number;      // 0-1, high-frequency absorption
  brightness: number;   // 0-1, initial high-freq content
}

export interface Scene {
  id: string;
  name: string;
  description: string;
  tagline: string;
  gradientFrom: string;
  gradientTo: string;
  gradientMid?: string;
  azimuth: number;     // degrees 0-360
  elevation: number;   // degrees -90 to 90
  distance: number;    // 0.1 to 10
  roomSize: number;    // 0-100 (UI percent)
  damping: number;     // 0-100 (UI percent)
  wetDry: number;      // 0-100 (UI percent)
  irParams: IRParams;
}

export const SCENES: Scene[] = [
  {
    id: 'studio-session',
    name: 'Studio Session',
    description: 'Velvet Studio',
    tagline: 'Intimate. Warm. Close.',
    gradientFrom: '#1a0a2e',
    gradientTo: '#0d111a',
    gradientMid: '#2d1b4e',
    azimuth: 30,
    elevation: 0,
    distance: 2,
    roomSize: 25,
    damping: 65,
    wetDry: 30,
    irParams: {
      decayTime: 0.8,
      preDelayMs: 8,
      roomSize: 0.25,
      damping: 0.70,
      brightness: 0.35,
    },
  },
  {
    id: 'pop-room',
    name: 'Pop Stage',
    description: 'Pop / Synthpop / K-pop',
    tagline: 'Bright. Energetic. Crisp.',
    gradientFrom: '#ff2a85',
    gradientTo: '#090B10',
    gradientMid: '#8a1c4a',
    azimuth: 0,
    elevation: 5,
    distance: 2.5,
    roomSize: 35,
    damping: 30,
    wetDry: 20,
    irParams: {
      decayTime: 1.2,
      preDelayMs: 15,
      roomSize: 0.40,
      damping: 0.35,
      brightness: 0.70,
    },
  },
  {
    id: 'rock-arena',
    name: 'Rock Arena',
    description: 'Rock / Metal / Alternative',
    tagline: 'Loud. Gritty. Massive.',
    gradientFrom: '#6b0000',
    gradientTo: '#000000',
    gradientMid: '#360000',
    azimuth: 0,
    elevation: 10,
    distance: 5,
    roomSize: 85,
    damping: 45,
    wetDry: 45,
    irParams: {
      decayTime: 2.8,
      preDelayMs: 25,
      roomSize: 0.85,
      damping: 0.40,
      brightness: 0.60,
    },
  },
  {
    id: 'hip-hop-studio',
    name: 'The Booth',
    description: 'Hip Hop / Trap / Rap',
    tagline: 'Punchy. Dry. Bass-heavy.',
    gradientFrom: '#1c1c1c',
    gradientTo: '#050505',
    gradientMid: '#383838',
    azimuth: 0,
    elevation: 0,
    distance: 1.5,
    roomSize: 15,
    damping: 80,
    wetDry: 15,
    irParams: {
      decayTime: 0.5,
      preDelayMs: 5,
      roomSize: 0.15,
      damping: 0.85,
      brightness: 0.20,
    },
  },
  {
    id: 'edm-club',
    name: 'Underground Club',
    description: 'EDM / Dance / House',
    tagline: 'Pulsing. Cavernous. Submerged.',
    gradientFrom: '#00fa9a',
    gradientTo: '#001a0d',
    gradientMid: '#006633',
    azimuth: 0,
    elevation: -10,
    distance: 4,
    roomSize: 70,
    damping: 40,
    wetDry: 60,
    irParams: {
      decayTime: 2.5,
      preDelayMs: 30,
      roomSize: 0.75,
      damping: 0.50,
      brightness: 0.40,
    },
  },
  {
    id: 'tokyo-jazz',
    name: 'Tokyo Jazz Club',
    description: 'Jazz / Swing / Fusion',
    tagline: 'Smoky. Resonant. Intimate.',
    gradientFrom: '#001a2d',
    gradientTo: '#090B10',
    gradientMid: '#003050',
    azimuth: 45,
    elevation: 5,
    distance: 3,
    roomSize: 50,
    damping: 40,
    wetDry: 48,
    irParams: {
      decayTime: 2.2,
      preDelayMs: 18,
      roomSize: 0.55,
      damping: 0.38,
      brightness: 0.55,
    },
  },
  {
    id: 'blues-lounge',
    name: 'Blues Lounge',
    description: 'Chicago / Delta Blues',
    tagline: 'Raw. Gritty. Soulful.',
    gradientFrom: '#1c2841',
    gradientTo: '#090B10',
    gradientMid: '#2c3e50',
    azimuth: -20,
    elevation: 2,
    distance: 3,
    roomSize: 40,
    damping: 50,
    wetDry: 35,
    irParams: {
      decayTime: 1.5,
      preDelayMs: 12,
      roomSize: 0.45,
      damping: 0.55,
      brightness: 0.45,
    },
  },
  {
    id: 'country-hall',
    name: 'Nashville Hall',
    description: 'Country / Bluegrass',
    tagline: 'Organic. Wooden. Wide.',
    gradientFrom: '#8b5a2b',
    gradientTo: '#090B10',
    gradientMid: '#5c3a21',
    azimuth: 0,
    elevation: 8,
    distance: 4,
    roomSize: 60,
    damping: 35,
    wetDry: 40,
    irParams: {
      decayTime: 1.8,
      preDelayMs: 22,
      roomSize: 0.65,
      damping: 0.30,
      brightness: 0.65,
    },
  },
  {
    id: 'rnb-lounge',
    name: 'Motown Room',
    description: 'R&B / Soul',
    tagline: 'Smooth. Warm. Deep.',
    gradientFrom: '#4b0082',
    gradientTo: '#090B10',
    gradientMid: '#300052',
    azimuth: 15,
    elevation: 0,
    distance: 2.5,
    roomSize: 30,
    damping: 70,
    wetDry: 25,
    irParams: {
      decayTime: 1.0,
      preDelayMs: 10,
      roomSize: 0.30,
      damping: 0.75,
      brightness: 0.30,
    },
  },
  {
    id: 'folk-acoustic',
    name: 'Acoustic Loft',
    description: 'Folk / Celtic',
    tagline: 'Airy. Natural. Clear.',
    gradientFrom: '#8fcb9b',
    gradientTo: '#090B10',
    gradientMid: '#5b8a65',
    azimuth: -15,
    elevation: 5,
    distance: 3.5,
    roomSize: 55,
    damping: 25,
    wetDry: 35,
    irParams: {
      decayTime: 1.6,
      preDelayMs: 15,
      roomSize: 0.60,
      damping: 0.20,
      brightness: 0.75,
    },
  },
  {
    id: 'world-stage',
    name: 'World Stage',
    description: 'Latin / Afrobeat / Raga',
    tagline: 'Expansive. Rhythmic. Open.',
    gradientFrom: '#e67300',
    gradientTo: '#090B10',
    gradientMid: '#8a4500',
    azimuth: 0,
    elevation: 12,
    distance: 6,
    roomSize: 75,
    damping: 35,
    wetDry: 50,
    irParams: {
      decayTime: 2.0,
      preDelayMs: 20,
      roomSize: 0.80,
      damping: 0.35,
      brightness: 0.55,
    },
  },
  {
    id: 'bollywood-cinema',
    name: 'Bollywood Cinema',
    description: 'Filmi / Indian Pop',
    tagline: 'Lush. Grand. Cinematic.',
    gradientFrom: '#ff1493',
    gradientTo: '#090B10',
    gradientMid: '#8a0a4c',
    azimuth: 0,
    elevation: 10,
    distance: 5.5,
    roomSize: 85,
    damping: 25,
    wetDry: 55,
    irParams: {
      decayTime: 2.4,
      preDelayMs: 25,
      roomSize: 0.90,
      damping: 0.25,
      brightness: 0.60,
    },
  },
  {
    id: 'red-rocks',
    name: 'Red Rocks',
    description: 'Open Air Amphitheatre',
    tagline: 'Vast. Majestic. Alive.',
    gradientFrom: '#2d0a00',
    gradientTo: '#090B10',
    gradientMid: '#4a1500',
    azimuth: 0,
    elevation: 15,
    distance: 5,
    roomSize: 80,
    damping: 20,
    wetDry: 60,
    irParams: {
      decayTime: 1.8,
      preDelayMs: 20,
      roomSize: 0.78,
      damping: 0.22,
      brightness: 0.65,
    },
  },
  {
    id: 'golden-brown',
    name: 'Golden Brown',
    description: 'Vintage Harpsichord Room',
    tagline: 'Warm. Vintage. Intimate.',
    gradientFrom: '#4a2511',
    gradientTo: '#090B10',
    gradientMid: '#8a4b1c',
    azimuth: 18,
    elevation: 5,
    distance: 2,
    roomSize: 35,
    damping: 60,
    wetDry: 25,
    irParams: {
      decayTime: 0.9,
      preDelayMs: 12,
      roomSize: 0.35,
      damping: 0.65,
      brightness: 0.40,
    },
  },
  {
    id: 'void',
    name: 'Void',
    description: 'Anechoic Chamber',
    tagline: 'Pure. Silent. Precise.',
    gradientFrom: '#050508',
    gradientTo: '#090B10',
    gradientMid: '#08090f',
    azimuth: 180,
    elevation: 0,
    distance: 1,
    roomSize: 0,
    damping: 100,
    wetDry: 2,
    irParams: {
      decayTime: 0.05,
      preDelayMs: 0,
      roomSize: 0.0,
      damping: 0.99,
      brightness: 0.01,
    },
  },
  {
    id: 'dreamer',
    name: 'Dreamer',
    description: 'Cave',
    tagline: 'Deep. Cavernous. Ethereal.',
    gradientFrom: '#001a1a',
    gradientTo: '#090B10',
    gradientMid: '#00332d',
    azimuth: 270,
    elevation: -20,
    distance: 6,
    roomSize: 90,
    damping: 10,
    wetDry: 78,
    irParams: {
      decayTime: 4.2,
      preDelayMs: 45,
      roomSize: 0.92,
      damping: 0.06,
      brightness: 0.28,
    },
  },
];

export function getSceneById(id: string): Scene | undefined {
  return SCENES.find((s) => s.id === id);
}
